export default class TagUtil {
  //登录
  static readonly LOGIN_LOCAL_SERVER: string = 'LOGIN_LOCAL_SERVER';
  static readonly IS_TEST_ENV: string = 'IS_TEST_ENV';
  static readonly USER_ACCOUNT: string = 'USER_ACCOUNT';
  static readonly USER_PASSWORD: string = 'USER_PASSWORD';
  static readonly USER_TOKEN: string = 'USER_TOKEN';
  static readonly USER_ID: string = 'USER_ID';
  static readonly USER_SCHOOL_ID: string = 'USER_SCHOOL_ID';
  static readonly USER_NAME: string = 'USER_NAME';
  static readonly USER_ROLE_NAME: string = 'USER_ROLE_NAME';
  static readonly USER_SIGN: string = 'USER_SIGN';
  //应用和前端相互调用
  static readonly LOGIN_FORGET_PSW: string = 'LOGIN_FORGET_PSW';
  static readonly HOME_APP_JUMP: string = 'HOME_APP_JUMP';
}
