import CommonUtil from '../../../../../library/src/main/ets/components/CommonUtil'

@Entry
@Component
struct Index {
  @State message: string = 'Hello World';

  build() {
    Row() {
      Column() {
        Text(this.message)
          .fontSize(50)
          .fontWeight(FontWeight.Bold)
          .onClick(()=>{
          CommonUtil.isFastClick(new Date().getTime())
        })
      }
      .width('100%')
    }
    .height('100%')
  }
}